export interface Antece {
  motivoconsulta: string;
  cuanvisito: string;
  motivo: string;
  cdcuantiempo: string;
  radiografias: string;
  cuantascuando: string;
  orgdentarios: string;
  cuantosporque: string;
  remplazo: string;
  comocuando: string;
  cirugias: string;
  tipos: string;
  proanestesia: string;
  quetipo: string;
  higieneoral: string;
  algvezhateni: string;
  explique: string;
  hospital: string;
  vismedult: string;
  paraque: string;
  drogas: string;
  cualesdr: string;
  hsig: string;
  reacalergicas: string;
  tipreac: string;
  cualesali: string;
  cualesd: string;
  cualesanes: string;
  cualesotr: string;
  consmedica: string;
  porque: string;
  obs: string;
  exploracion: string;
  deschigieneoral: string;
  calculos: string;
  exploracionradiografica: string;
  porqueOrganos	:string;
  siReemplazoOrganos	:string;
  comoReemplazoOrganos	:string;
  cuandoReemplazoOrganos	:string;
  cualesCirugias	:string;
  problemasAnestesia	:string;
  cualesProblemas	:string;
  cuidadoHospital	:string;
  cuidadoMedico	:string;
  cuidadoHistorial	:string;
  cuidadoParaque	:string;
  cualesDrogas	:string;
  cualesHemorragias	:string;
  cualesAlergias	:string;
  consultaPorque	:string;
  organos:string;
  cuantosOrganos:string;
  vistmedult:string;
  recalergicas:string;
  paciente: string;
  radiografia: string;
  malestar: string;
  hemorragiass: string;
  cuantasRadio: string;
  cuandoRadio: string;
  id: string;
  cavidad:string;
  higieneo:string;
}
