export interface Antece {
    motivoconsulta: string;
    cuanvisito: string;
    motivo: string;
    cdcuantiempo: string;
    radiografias: string;
    cuantascuando: string;
    orgdentarios: string;
    remplazo: string;
    comocuando: string;
    cirugias: string;
    tipos: string;
    proanestecia: string;
    quetipo: string;
    higieneoral: string;
    algvezhateni: string;
    explique: string;
    cuidadomedico: string;
    hospital: string;
    vismedult: string;
    paraque: string;
    drogas: string;
    cualesdr: string;
    hemorragias: string;
    hsig: string;
    reacalergicas: string;
    cualesali: string;
    cualesd: string;
    cualesanes: string;
    cualesotr; string;
    consmedica: string;
    porque: string;
    obs: string;
    exploracion: string;
    deschigieneoral: string;
    calculos: string;
    exploracionradiografica: string;
  }
  