import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { DiagnosticoService } from './diagnosticopulpar.service';

@Component({
  selector: 'app-diagnosticopulpar',
  templateUrl: './diagnosticopulpar.component.html',
  styleUrls: ['./diagnosticopulpar.component.css']
})
export class DiagnosticopulparComponent implements OnInit {
  form: FormGroup;
  constructor(public diagnosticoService: DiagnosticoService) { }

  ngOnInit() {
    this.form = new FormGroup({
      organoa: new FormControl(null, {validators: [Validators.required] }),
      content: new FormControl(null, { validators: [Validators.required] }),
      tipodedolor: new FormControl(null, { validators: [Validators.required] }),
      episodios: new FormControl(null, { validators: [Validators.required] }),
      percusion: new FormControl(null, { validators: [Validators.required] }),
      movilidad: new FormControl(null, { validators: [Validators.required] }),
      cambiodecolor: new FormControl(null, { validators: [Validators.required] }),
      trufaccionintra: new FormControl(null, { validators: [Validators.required] }),
      trumefaccionextra: new FormControl(null, { validators: [Validators.required] }),
      fisura: new FormControl(null, { validators: [Validators.required] }),
      reaccionpulpar: new FormControl(null, { validators: [Validators.required] }),
      testcavit: new FormControl(null, { validators: [Validators.required] }),
      observaciones: new FormControl(null, { validators: [Validators.required] }),
      organob: new FormControl(null, { validators: [Validators.required] }),
      caries: new FormControl(null, { validators: [Validators.required] }),
      trauma: new FormControl(null, { validators: [Validators.required] }),
      enfperiodonta: new FormControl(null, { validators: [Validators.required] }),
      obtdefectuosa: new FormControl(null, { validators: [Validators.required] }),
      fractura: new FormControl(null, { validators: [Validators.required] }),
      corona: new FormControl(null, { validators: [Validators.required] }),
      raiz: new FormControl(null, { validators: [Validators.required] }),
      otro: new FormControl(null, { validators: [Validators.required] }),
      otro2: new FormControl(null, { validators: [Validators.required] }),
      otro3: new FormControl(null, { validators: [Validators.required] }),
      organoc: new FormControl(null, { validators: [Validators.required] }),
      calcificaciones: new FormControl(null, { validators: [Validators.required] }),
      corona2: new FormControl(null, { validators: [Validators.required] }),
      raiz2: new FormControl(null, { validators: [Validators.required] }),
      resorcion: new FormControl(null, { validators: [Validators.required] }),
      interno: new FormControl(null, { validators: [Validators.required] }),
      externo: new FormControl(null, { validators: [Validators.required] }),
      refacciones: new FormControl(null, { validators: [Validators.required] }),
      penapico: new FormControl(null, { validators: [Validators.required] }),
      radicular: new FormControl(null, { validators: [Validators.required] }),
      obturaciondefectuosa2: new FormControl(null, { validators: [Validators.required] }),
      organodentario: new FormControl(null, { validators: [Validators.required] }),
      vital: new FormControl(null, { validators: [Validators.required] }),
      reversible: new FormControl(null, { validators: [Validators.required] }),
      irreversible: new FormControl(null, { validators: [Validators.required] }),
      novital: new FormControl(null, { validators: [Validators.required] }),
      aguda: new FormControl(null, { validators: [Validators.required] }),
      cronica: new FormControl(null, { validators: [Validators.required] }),
    });
  }
  addDiagnostico() {
    this.diagnosticoService.addDiagnostico(
      this.form.value.organoa,
      this.form.value.content,
      this.form.value.tipodedolor		,
      this.form.value.episodios		,
      this.form.value.percusion		,
      this.form.value.movilidad		,
      this.form.value.cambiodecolor		,
      this.form.value.trumefaccionintra		,
      this.form.value.trumefaccionextra		,
      this.form.value.fisura		,
      this.form.value.    reaccionpulpar		,
      this.form.value.	    testcavit		,
      this.form.value.	    observaciones		,
      this.form.value.	    organob		,
      this.form.value.	    caries		,
      this.form.value.	    trauma		,
      this.form.value.	    enfperiodonta		,
      this.form.value.	    obtdefectuosa		,
      this.form.value.	    fractura		,
      this.form.value.	    corona		,
      this.form.value.	    raiz		,
      this.form.value.	    otro		,
      this.form.value.	    otro2		,
      this.form.value.	    otro3		,
      this.form.value.	    organoc		,
      this.form.value.	    calcificaciones		,
      this.form.value.	    corona2		,
      this.form.value.	    raiz2		,
      this.form.value.	    resorcion		,
      this.form.value.	    interno		,
      this.form.value.	    externo		,
      this.form.value.	    refacciones		,
      this.form.value.	    penapico		,
      this.form.value.	    radicular		,
      this.form.value.	    obturaciondefectuosa2		,
      this.form.value.	    organodentario		,
      this.form.value.	    vital		,
      this.form.value.	    reversible		,
      this.form.value.	    irreversible		,
      this.form.value.	    novital		,
      this.form.value.	    aguda		,
      this.form.value.	    cronica,
    );
  }
}
